server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academy_trip
    username: postgres
    password: 070515294545
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update