server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academy_trip
    username: postgres
    password: 070515294545
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

auth:
  header: Authorization
  jwt:
    secret: XUlkPxDr620G6sz2OC40sXvkaqzeFeeFTm93A0BMLbWXFKb5SzFdTAsJgLoOzSWTUAhcTvoe5KiYPDg3wif1Ew
#    algorithm: HS512
    expiration-ms: 7200000 # 2 hours